# Generated by Django 4.0.3 on 2022-04-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('identity', models.CharField(max_length=100)),
                ('has_purchased', models.BooleanField(default=False)),
                ('gmt_purchased', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
